# Generated by Django 3.2.9 on 2021-11-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('removed', 'Rem'), ('tos', 'Tos')], default='removed', max_length=10)),
                ('loc', models.OneToOneField(max_length=60, on_delete=django.db.models.deletion.CASCADE, to='mainapp.location')),
            ],
        ),
    ]
