# Generated by Django 3.2.9 on 2021-11-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('id', 'loc')},
        ),
    ]
